Fixing datatype of properties containing SKOS Concepts
iptc/sport-schema pull request #185
Opened 2024-04-30 07:46 UTC by bquinn

This was a bug in the original schema so the change doesn't need a Standards Committee vote.

Also updating version number to 1.0.1 throughout and updating dates.

2024-04-30 08:31 UTC, paulwilton requested changes
the ObjectProperty changes look good
however line 245 range sport:event should be sport:Event

2024-04-30 08:31 UTC, paulwilton commented on ontologies/iptc-sport-ontology.ttl
the ObjectProperty changes look good
however line 245  range  sport:event should be sport:Event

2024-04-30 08:48 UTC, bquinn commented on ontologies/iptc-sport-ontology.ttl
Fixed - thanks! I forgot that you had reported this already...

2024-05-07 13:29 UTC, bquinn commented
We also decided to change the versioning approach: #186

2024-05-14 13:47 UTC, merged